// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	primetime "github.com/sosljuk8/analytics/internal/handler/primetime"
	"github.com/sosljuk8/analytics/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.APIAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/primetime/request",
					Handler: primetime.ListHandler(serverCtx),
				},
			}...,
		),
	)
}
