// Code generated by ent, DO NOT EDIT.

package ent

import "go.uber.org/zap"

// MessageReader provides Message getters.
type MessageReader interface {
	GetID() int64

	GetDirection() string

	GetSent() string

	GetMailboxId() int

	GetCrmRid() int
}

// MessageWriter provides Message setters.
type MessageWriter interface {
	SetDirection(string)

	SetSent(string)

	SetMailboxId(int)

	SetCrmRid(int)
}

// Getters and setters for the fields of the Message.

func (m *Message) SetDirection(v string) {

	m.Direction = v

}

// GetDirection returns the Direction value.
// If the Direction  is nil zero value will be returned.
func (m *Message) GetDirection() string {

	return m.Direction

}

func (m *Message) SetSent(v string) {

	m.Sent = v

}

// GetSent returns the Sent value.
// If the Sent  is nil zero value will be returned.
func (m *Message) GetSent() string {

	return m.Sent

}

func (m *Message) SetMailboxId(v int) {

	m.MailboxId = v

}

// GetMailboxId returns the MailboxId value.
// If the MailboxId  is nil zero value will be returned.
func (m *Message) GetMailboxId() int {

	return m.MailboxId

}

func (m *Message) SetCrmRid(v int) {

	m.CrmRid = v

}

// GetCrmRid returns the CrmRid value.
// If the CrmRid  is nil zero value will be returned.
func (m *Message) GetCrmRid() int {

	return m.CrmRid

}

// SetID sets the id field value.
func (m *Message) SetID(v int64) {
	m.ID = v
}

// GetID returns the id field value.
func (m *Message) GetID() int64 {
	return m.ID
}

// SetMessageID is alias of SetID used in intersected interfaces.
func (m *Message) SetMessageID(v int64) {
	m.SetID(v)
}

// GetMessageID is alias of GetID used in intersected interfaces.
func (m *Message) GetMessageID() int64 {
	return m.GetID()
}

// Zap field providing dump of Message properties to zap fields
// Sensitive fields are skipped by ent generated Message.String()
func (m *Message) Zap() zap.Field {
	return zap.String("Message", m.String())
}
