// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sosljuk8/analytics/orm/ent/message"
)

// Message is the model entity for the Message schema.
type Message struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Direction holds the value of the "Direction" field.
	Direction string `json:"direction"`
	// Sent holds the value of the "Sent" field.
	Sent string `json:"sent"`
	// MailboxId holds the value of the "MailboxId" field.
	MailboxId int `json:"mailboxId"`
	// CrmRid holds the value of the "CrmRid" field.
	CrmRid       int `json:"crmRid"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Message) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case message.FieldID, message.FieldMailboxId, message.FieldCrmRid:
			values[i] = new(sql.NullInt64)
		case message.FieldDirection, message.FieldSent:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Message fields.
func (m *Message) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case message.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int64(value.Int64)
		case message.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Direction", values[i])
			} else if value.Valid {
				m.Direction = value.String
			}
		case message.FieldSent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Sent", values[i])
			} else if value.Valid {
				m.Sent = value.String
			}
		case message.FieldMailboxId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field MailboxId", values[i])
			} else if value.Valid {
				m.MailboxId = int(value.Int64)
			}
		case message.FieldCrmRid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field CrmRid", values[i])
			} else if value.Valid {
				m.CrmRid = int(value.Int64)
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Message.
// This includes values selected through modifiers, order, etc.
func (m *Message) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// Update returns a builder for updating this Message.
// Note that you need to call Message.Unwrap() before calling this method if this Message
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Message) Update() *MessageUpdateOne {
	return NewMessageClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Message entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Message) Unwrap() *Message {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Message is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Message) String() string {
	var builder strings.Builder
	builder.WriteString("Message(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("Direction=")
	builder.WriteString(m.Direction)
	builder.WriteString(", ")
	builder.WriteString("Sent=")
	builder.WriteString(m.Sent)
	builder.WriteString(", ")
	builder.WriteString("MailboxId=")
	builder.WriteString(fmt.Sprintf("%v", m.MailboxId))
	builder.WriteString(", ")
	builder.WriteString("CrmRid=")
	builder.WriteString(fmt.Sprintf("%v", m.CrmRid))
	builder.WriteByte(')')
	return builder.String()
}

// Messages is a parsable slice of Message.
type Messages []*Message
