// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/go-playground/validator"
)

var Validate = validator.New()

// Validate Message with struct literals
func (n *Message) Validate() error {
	return Validate.Struct(n)
}

// Validate MessageMutation with Message struct literals
func (m *MessageMutation) Validate() error {
	obj := &Message{}

	if v, ok := m.Direction(); ok {
		obj.Direction = v
	}

	if v, ok := m.Sent(); ok {
		obj.Sent = v
	}

	if v, ok := m.MailboxId(); ok {
		obj.MailboxId = v
	}

	if v, ok := m.CrmRid(); ok {
		obj.CrmRid = v
	}

	return Validate.Struct(obj)
}
