// Code generated by ent, DO NOT EDIT.

package message

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldSent holds the string denoting the sent field in the database.
	FieldSent = "sent"
	// FieldMailboxId holds the string denoting the mailboxid field in the database.
	FieldMailboxId = "mailbox_id"
	// FieldCrmRid holds the string denoting the crmrid field in the database.
	FieldCrmRid = "crm_rid"
	// Table holds the table name of the message in the database.
	Table = "messages"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldDirection,
	FieldSent,
	FieldMailboxId,
	FieldCrmRid,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Message queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDirection orders the results by the Direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// BySent orders the results by the Sent field.
func BySent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSent, opts...).ToFunc()
}

// ByMailboxId orders the results by the MailboxId field.
func ByMailboxId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMailboxId, opts...).ToFunc()
}

// ByCrmRid orders the results by the CrmRid field.
func ByCrmRid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCrmRid, opts...).ToFunc()
}
